import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { NavLinks } from "@/app/ui/nav-links";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Psychonaut Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="w-screen h-screen flex flex-col overflow-x-hidden scrollbar-color scrollbar-thumb-gray scrollbar-track-transparent">
          <NavLinks />
          {children}
        </div>
        <div className="w-screen h-screen top-0 left-0 fixed bg-wallpaper bg-cover -z-50 pointer-events-none"></div>
      </body>
    </html>
  );
}
